/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grocery_shopping;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Sneha
 */
public class finallist extends javax.swing.JFrame {
    java.sql.Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String currentUser; 
    
    
    /* Creates new form finallist
     */
    public finallist(String user) {
        initComponents();
        this.currentUser = user;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbutt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        feedtxt = new javax.swing.JTextField();
        feedbutt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        backbutt1 = new javax.swing.JButton();

        backbutt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        backbutt.setForeground(new java.awt.Color(0, 153, 153));
        backbutt.setText("BACK TO LIST");
        backbutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Thank You for Using Our Grocery Shopping Assistant!\n\nDear User,\n\nWe want to express our heartfelt gratitude for choosing our grocery shopping assistant to manage your shopping needs. Your trust and \nsupport mean the world to us.\n\nAs you head out to shop for your groceries, we hope that our application has made your experience more convenient and efficient. With your \ndetailed list in hand, you're all set to tackle your shopping trip with ease.\n\nRemember, our application is designed to adapt to your needs. Whether you're shopping at your favorite local store or exploring new options,\n our assistant is here to make your grocery shopping experience hassle-free.\n\nWe value your feedback and suggestions, as they help us improve and enhance our services. If you have any comments or ideas for us, please \ndon't hesitate to reach out.\n\n Your input is invaluable to us.\n\nOnce again, thank you for choosing our grocery shopping assistant. We look forward to serving you again in the future. Happy shopping!\n\nWarm regards,\n\nSneha, Gargi, Saniya");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Feedback:");

        feedtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedtxtActionPerformed(evt);
            }
        });

        feedbutt.setBackground(new java.awt.Color(0, 153, 153));
        feedbutt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        feedbutt.setForeground(new java.awt.Color(255, 255, 255));
        feedbutt.setText("Submit");
        feedbutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbuttMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("See the list");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(list);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Click here once shopping is done!!");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        backbutt1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        backbutt1.setForeground(new java.awt.Color(0, 153, 153));
        backbutt1.setText("BACK TO LIST");
        backbutt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbutt1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(feedbutt)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backbutt1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(backbutt1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(feedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feedbutt))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feedtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feedtxtActionPerformed

    private void feedbuttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbuttMouseClicked
        String feed= feedtxt.getText();
        if(feed.isEmpty()){
            JOptionPane.showMessageDialog(null,"data is required");
        }else{
            try{
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "sneha");
                String q = "INSERT INTO FEEDBACK VALUES (?,?)";
                pst = conn.prepareStatement(q);
                pst.setString(1, currentUser);
                pst.setString(2, feed);
                rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Thank you");
                }
            }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error:" );
                }
        }
    }//GEN-LAST:event_feedbuttMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "sneha");
            String q = "SELECT * FROM TOBUY WHERE USERNAME = ?";
            pst = conn.prepareStatement(q);
            pst.setString(1, currentUser);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel)list.getModel();
            int col = rsmd.getColumnCount();
            String[] colName = new String[col];
            for (int i = 0; i < col; i++) {
                colName[i] = rsmd.getColumnName(i + 1);
            }
            model.setColumnIdentifiers(colName);
            String user, itemname, quantity;
            while (rs.next()) {
                user = rs.getString(1);
                itemname = rs.getString(2);
                quantity = rs.getString(3);
                String[] row = {user, itemname, quantity};
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " );
        }
   

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "sneha");
            String q = "DELETE FROM TOBUY WHERE USERNAME = ?";
            pst = conn.prepareStatement(q);
            pst.setString(1, currentUser);
            int rowsDeleted = pst.executeUpdate();
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(null, "List cleared");
            } else {
                JOptionPane.showMessageDialog(null, "No items found to delete");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " );
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backbuttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttMouseClicked
        this.dispose();
        landing landingframe = new landing(currentUser);
        landingframe.setVisible(true);
        landingframe.pack();
        landingframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_backbuttMouseClicked

    private void backbutt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbutt1MouseClicked
        this.dispose();
        landing landingframe = new landing(currentUser);
        landingframe.setVisible(true);
        landingframe.pack();
        landingframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_backbutt1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finallist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finallist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finallist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finallist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finallist("currentUser").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutt;
    private javax.swing.JButton backbutt1;
    private javax.swing.JButton feedbutt;
    private javax.swing.JTextField feedtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable list;
    // End of variables declaration//GEN-END:variables
}
