package grocery_shopping;
import java.sql.*;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sneha
 */
public class landing extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    PreparedStatement addst= null;
    PreparedStatement removeStmt = null;
    ResultSet rs = null;
    String currentUser; 
   
    public landing(String user) {
        initComponents();
        this.currentUser= user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantitytxt = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        favitemtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        favquantxt = new javax.swing.JComboBox<>();
        favadd = new javax.swing.JButton();
        favdelbut = new javax.swing.JButton();
        finalbutt = new javax.swing.JButton();
        Submitbutt = new javax.swing.JButton();
        itemtxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addallergy = new javax.swing.JButton();
        adelbutt = new javax.swing.JButton();
        aitemtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quantitytxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Favourite/Frequent orders");

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Item name:");

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity:");

        favquantxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        favadd.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        favadd.setText("Add");
        favadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favaddMouseClicked(evt);
            }
        });
        favadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favaddActionPerformed(evt);
            }
        });

        favdelbut.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        favdelbut.setText("Delete");
        favdelbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favdelbutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(favquantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(favadd)
                                    .addComponent(favitemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(favdelbut)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(favitemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(favquantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(favadd)
                            .addComponent(favdelbut))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        finalbutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        finalbutt.setForeground(new java.awt.Color(0, 153, 153));
        finalbutt.setText("Generate the final shopping list ");
        finalbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalbuttActionPerformed(evt);
            }
        });

        Submitbutt.setBackground(new java.awt.Color(204, 204, 204));
        Submitbutt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submitbutt.setText("Submit");
        Submitbutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitbuttMouseClicked(evt);
            }
        });

        itemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemtxtActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel17.setText("Enter the quantity:");

        jLabel18.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel18.setText("Enter the item name:");

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Allergies");

        jLabel21.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Item name:");

        addallergy.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        addallergy.setText("Add");
        addallergy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addallergyMouseClicked(evt);
            }
        });
        addallergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addallergyActionPerformed(evt);
            }
        });

        adelbutt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        adelbutt.setText("Delete");
        adelbutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adelbuttMouseClicked(evt);
            }
        });
        adelbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adelbuttActionPerformed(evt);
            }
        });

        aitemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aitemtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(addallergy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adelbutt))
                            .addComponent(aitemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(240, 240, 240)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel20))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(aitemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addallergy)
                    .addComponent(adelbutt))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel2.setText("Kindly enter the details to ease your shopping process");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("            You can enter all your allergies (if any) and favourites when you use this application for the first time. Later on you can add or delete any item.");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Checkout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Are you experiencing difficulties gathering all the ingredients needed to make various international recipes?");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Checkout few international dishes and add them in your list");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Submitbutt)
                                    .addComponent(itemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(finalbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(itemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Submitbutt)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addComponent(finalbutt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void favaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favaddActionPerformed

    private void finalbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalbuttActionPerformed
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "sneha");
            String addQuery = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT USERNAME, ITEM, QUANTITY FROM FAV WHERE ITEM NOT IN (SELECT ITEM FROM TOBUY)";
            addst = conn.prepareStatement(addQuery);
            addst.executeUpdate();
            addst.close();
            
            String removeQuery = "DELETE FROM TOBUY WHERE ITEM IN (SELECT ITEM FROM ALLERGY)";
            removeStmt = conn.prepareStatement(removeQuery);
            removeStmt.executeUpdate();
            removeStmt.close();
            JOptionPane.showMessageDialog(null, "List generated successfully.");
            
            this.dispose();
            finallist finalframe = new finallist(currentUser);
            finalframe.setVisible(true);
            finalframe.pack();
            finalframe.setLocationRelativeTo(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, " ");
        }
    }//GEN-LAST:event_finalbuttActionPerformed

    private void SubmitbuttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitbuttMouseClicked
        String itemname = itemtxt.getText();
        String quantity = quantitytxt.getSelectedItem().toString();
        if(itemname.isEmpty()||quantity.isEmpty()){
            JOptionPane.showMessageDialog(null,"All data is required");
        }else{
            try{
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "SELECT * FROM TOBUY WHERE ITEM =? AND QUANTITY =? ";
                pst = conn.prepareStatement(q1);
                pst.setString(1, itemname);
                pst.setString(2, quantity);
                rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"Item already added in the list");
                }else{
                    try{
                        String q2 = "INSERT INTO TOBUY VALUES(?,?,?) ";
                        pst = conn.prepareStatement(q2);
                        pst.setString(1, currentUser);
                        pst.setString(2, itemname);
                        pst.setString(3,quantity);
                        ResultSet rs1 = pst.executeQuery();
                        if(rs1.next()){
                            JOptionPane.showMessageDialog(null,"Item added");
                            this.dispose();
                            landing landingframe = new landing(currentUser);
                            landingframe.setVisible(true);
                            landingframe.pack();
                            landingframe.setLocationRelativeTo(null);
                        }else{
                            JOptionPane.showMessageDialog(null," ");
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_SubmitbuttMouseClicked

    private void itemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemtxtActionPerformed

    private void addallergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addallergyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addallergyActionPerformed

    private void adelbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adelbuttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adelbuttActionPerformed

    private void aitemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aitemtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aitemtxtActionPerformed

    private void favaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favaddMouseClicked
        String itemfav = favitemtxt.getText();
        String quanfav = favquantxt.getSelectedItem().toString();
        if(itemfav.isEmpty()||quanfav.isEmpty()){
        JOptionPane.showMessageDialog(null,"All data is required");
        }else{
            try{
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "SELECT * FROM FAV WHERE ITEM =? AND QUANTITY =? ";
                pst = conn.prepareStatement(q1);
                pst.setString(1, itemfav);
                pst.setString(2, quanfav);
                rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"Item already added in the list");
                }else{
                    try{
                        String q2 = "INSERT INTO FAV VALUES(?,?,?) ";
                        pst = conn.prepareStatement(q2);
                        pst.setString(1, currentUser);
                        pst.setString(2, itemfav);
                        pst.setString(3,quanfav);
                        ResultSet rs1 = pst.executeQuery();
                        if(rs1.next()){
                            JOptionPane.showMessageDialog(null,"Item added");
                            this.dispose();
                            landing landingframe = new landing(currentUser);
                            landingframe.setVisible(true);
                            landingframe.pack();
                            landingframe.setLocationRelativeTo(null);
                        }else{
                            JOptionPane.showMessageDialog(null," ");
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        
        }
    }//GEN-LAST:event_favaddMouseClicked

    private void favdelbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favdelbutMouseClicked
        String itemfav = favitemtxt.getText();
        String quanfav = favquantxt.getSelectedItem().toString();
        if(itemfav.isEmpty()||quanfav.isEmpty()){
        JOptionPane.showMessageDialog(null,"All data is required");
        }else{
            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "sneha");
                String checkQuery = "SELECT * FROM FAV WHERE USERNAME = ? AND ITEM = ? AND QUANTITY = ?";
                pst = conn.prepareStatement(checkQuery);
                pst.setString(1, currentUser);
                pst.setString(2, itemfav);
                pst.setString(3, quanfav);
                rs = pst.executeQuery();

                if (rs.next()) {
                    String delQuery = "DELETE FROM FAV WHERE USERNAME = ? AND ITEM = ?";
                    pst = conn.prepareStatement(delQuery);
                    pst.setString(1, currentUser);
                    pst.setString(2, itemfav);
                    int rowsAffected = pst.executeUpdate();

                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Item deleted successfully");
                        this.dispose();
                        landing landingframe = new landing(currentUser);
                        landingframe.setVisible(true);
                        landingframe.pack();
                        landingframe.setLocationRelativeTo(null);
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to delete the item");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Item is not present in the favorite list");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error " );
            }
        }
    }//GEN-LAST:event_favdelbutMouseClicked

    private void addallergyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addallergyMouseClicked
        String aitem = aitemtxt.getText();
        if(aitem.isEmpty()){
        JOptionPane.showMessageDialog(null,"Data is required");
        }else{
            try{
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "SELECT * FROM ALLERGY WHERE USERNAME= ? AND ITEM =?  ";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser);
                pst.setString(2,aitem);
                rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"Item already added in the list");
                }else{
                    try{
                        String q2 = "INSERT INTO ALLERGY VALUES(?,?) ";
                        pst = conn.prepareStatement(q2);
                        pst.setString(1, currentUser);
                        pst.setString(2, aitem);
                        ResultSet rs1 = pst.executeQuery();
                        if(rs1.next()){
                            JOptionPane.showMessageDialog(null,"Item added");
                            this.dispose();
                            landing landingframe = new landing(currentUser);
                            landingframe.setVisible(true);
                            landingframe.pack();
                            landingframe.setLocationRelativeTo(null);
                        }else{
                            JOptionPane.showMessageDialog(null," ");
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        
        }
    }//GEN-LAST:event_addallergyMouseClicked

    private void adelbuttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adelbuttMouseClicked
        String aitem = aitemtxt.getText();
        if(aitem.isEmpty()){
            JOptionPane.showMessageDialog(null,"Data is required");
        }else{
            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "sneha");
                String checkQuery = "SELECT * FROM ALLERGY WHERE USERNAME = ? AND ITEM = ?";
                pst = conn.prepareStatement(checkQuery);
                pst.setString(1, currentUser);
                pst.setString(2, aitem);
                rs = pst.executeQuery();
                if (rs.next()) {
                    String delQuery = "DELETE FROM ALLERGY WHERE USERNAME = ? AND ITEM = ?";
                    pst = conn.prepareStatement(delQuery);
                    pst.setString(1, currentUser);
                    pst.setString(2, aitem);
                    int rowsAffected = pst.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Item deleted successfully");
                        this.dispose();
                        landing landingframe = new landing(currentUser);
                        landingframe.setVisible(true);
                        landingframe.pack();
                        landingframe.setLocationRelativeTo(null);
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to delete the item");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Item is not present in the allergy list");
                }
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " );
            }
        }
     }//GEN-LAST:event_adelbuttMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            recipe recipeframe = new recipe(currentUser);
            recipeframe.setVisible(true);
            recipeframe.pack();
            recipeframe.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landing("currentUser").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submitbutt;
    private javax.swing.JButton addallergy;
    private javax.swing.JButton adelbutt;
    private javax.swing.JTextField aitemtxt;
    private javax.swing.JButton favadd;
    private javax.swing.JButton favdelbut;
    private javax.swing.JTextField favitemtxt;
    private javax.swing.JComboBox<String> favquantxt;
    private javax.swing.JButton finalbutt;
    private javax.swing.JTextField itemtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox<String> quantitytxt;
    // End of variables declaration//GEN-END:variables
}
