package grocery_shopping;
import java.sql.*;

import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sneha
 */
public class recipe extends javax.swing.JFrame {
    java.sql.Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String currentUser; 

    /**
     * Creates new form recipe
     */
    public recipe(String user) {
        initComponents();
        this.currentUser= user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pizza = new javax.swing.JButton();
        pasta = new javax.swing.JButton();
        burger = new javax.swing.JButton();
        sandwich = new javax.swing.JButton();
        fries = new javax.swing.JButton();
        garlic = new javax.swing.JButton();
        cheeseballs = new javax.swing.JButton();
        croissant = new javax.swing.JButton();
        spaghetti = new javax.swing.JButton();
        friedrice = new javax.swing.JButton();
        soup = new javax.swing.JButton();
        kungpaosauce = new javax.swing.JButton();
        sushi = new javax.swing.JButton();
        dumplings = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backbutt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pizza.setBackground(new java.awt.Color(204, 204, 204));
        pizza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pizza.setText("PIZZA");
        pizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaMouseClicked(evt);
            }
        });
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });

        pasta.setBackground(new java.awt.Color(204, 204, 204));
        pasta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pasta.setText("PASTA");
        pasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pastaMouseClicked(evt);
            }
        });
        pasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastaActionPerformed(evt);
            }
        });

        burger.setBackground(new java.awt.Color(204, 204, 204));
        burger.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        burger.setText("BURGER");
        burger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                burgerMouseClicked(evt);
            }
        });

        sandwich.setBackground(new java.awt.Color(204, 204, 204));
        sandwich.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sandwich.setText("SANDWICH");
        sandwich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sandwichMouseClicked(evt);
            }
        });

        fries.setBackground(new java.awt.Color(204, 204, 204));
        fries.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fries.setText("FRIES");
        fries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friesMouseClicked(evt);
            }
        });

        garlic.setBackground(new java.awt.Color(204, 204, 204));
        garlic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        garlic.setText("GARLIC BREAD");
        garlic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                garlicMouseClicked(evt);
            }
        });
        garlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garlicActionPerformed(evt);
            }
        });

        cheeseballs.setBackground(new java.awt.Color(204, 204, 204));
        cheeseballs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cheeseballs.setText("CHEESE BALLS");
        cheeseballs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cheeseballsMouseClicked(evt);
            }
        });

        croissant.setBackground(new java.awt.Color(204, 204, 204));
        croissant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        croissant.setText("CROISSANT");
        croissant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                croissantMouseClicked(evt);
            }
        });

        spaghetti.setBackground(new java.awt.Color(204, 204, 204));
        spaghetti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        spaghetti.setText("SPAGHETTI");
        spaghetti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spaghettiMouseClicked(evt);
            }
        });

        friedrice.setBackground(new java.awt.Color(204, 204, 204));
        friedrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        friedrice.setText("FRIED RICE");
        friedrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friedriceMouseClicked(evt);
            }
        });

        soup.setBackground(new java.awt.Color(204, 204, 204));
        soup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soup.setText("SOUP");
        soup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soupMouseClicked(evt);
            }
        });

        kungpaosauce.setBackground(new java.awt.Color(204, 204, 204));
        kungpaosauce.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kungpaosauce.setText("KUNG PAO SAUCE");
        kungpaosauce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kungpaosauceMouseClicked(evt);
            }
        });
        kungpaosauce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kungpaosauceActionPerformed(evt);
            }
        });

        sushi.setBackground(new java.awt.Color(204, 204, 204));
        sushi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sushi.setText("SUSHI");
        sushi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sushiMouseClicked(evt);
            }
        });

        dumplings.setBackground(new java.awt.Color(204, 204, 204));
        dumplings.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dumplings.setText("DUMPLINGS");
        dumplings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dumplingsMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("LIST OF DISHES");

        backbutt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        backbutt.setForeground(new java.awt.Color(0, 153, 153));
        backbutt.setText("BACK TO LIST");
        backbutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Please click on the dish for which you want to add ingredients to your list.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backbutt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pizza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(burger)
                            .addComponent(fries, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(garlic)
                            .addComponent(sushi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(croissant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kungpaosauce, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(soup, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(friedrice)
                                .addComponent(spaghetti)
                                .addComponent(sandwich)
                                .addComponent(cheeseballs))
                            .addComponent(dumplings))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dumplings, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pizza))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasta)
                    .addComponent(sandwich))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burger)
                    .addComponent(spaghetti))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(croissant)
                    .addComponent(friedrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soup, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fries))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(garlic)
                    .addComponent(kungpaosauce))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sushi)
                    .addComponent(cheeseballs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(backbutt)
                .addGap(36, 36, 36))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pastaActionPerformed

    private void garlicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garlicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_garlicActionPerformed

    private void kungpaosauceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kungpaosauceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kungpaosauceActionPerformed

    private void backbuttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttMouseClicked
        this.dispose();
        landing landingframe = new landing(currentUser);
        landingframe.setVisible(true);
        landingframe.pack();
        landingframe.setLocationRelativeTo(null);       
    }//GEN-LAST:event_backbuttMouseClicked

    private void pizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaMouseClicked

            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'pizza'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
            
    }//GEN-LAST:event_pizzaMouseClicked

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pizzaActionPerformed

    private void pastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pastaMouseClicked
            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'pasta'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
                  
    }//GEN-LAST:event_pastaMouseClicked

    private void burgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burgerMouseClicked
            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'burger'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
             
    }//GEN-LAST:event_burgerMouseClicked

    private void croissantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_croissantMouseClicked
            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'croissant'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
    }//GEN-LAST:event_croissantMouseClicked

    private void friesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friesMouseClicked
            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'fries'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
    }//GEN-LAST:event_friesMouseClicked

    private void garlicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_garlicMouseClicked
            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'garlic bread'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
    }//GEN-LAST:event_garlicMouseClicked

    private void cheeseballsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheeseballsMouseClicked
      try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'cheese balls'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
          
    }//GEN-LAST:event_cheeseballsMouseClicked

    private void kungpaosauceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kungpaosauceMouseClicked
try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'kung pao sauce'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
          
    }//GEN-LAST:event_kungpaosauceMouseClicked

    private void soupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soupMouseClicked
try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'soup'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
    }//GEN-LAST:event_soupMouseClicked

    private void friedriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friedriceMouseClicked
try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'spaghetti'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
    }//GEN-LAST:event_friedriceMouseClicked

    private void sandwichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sandwichMouseClicked
        try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'sandwich'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
      
    }//GEN-LAST:event_sandwichMouseClicked

    private void dumplingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dumplingsMouseClicked
try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'dumplings'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
    }//GEN-LAST:event_dumplingsMouseClicked

    private void sushiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sushiMouseClicked
      try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'sushi'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    
    }//GEN-LAST:event_sushiMouseClicked

    private void spaghettiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spaghettiMouseClicked
            try {
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sneha");
                String q1 = "INSERT INTO TOBUY (USERNAME, ITEM, QUANTITY) SELECT ?, INGREDIENTS, QUANTITY FROM RECIPE WHERE DISH_NAME = 'spaghetti'";
                pst = conn.prepareStatement(q1);
                pst.setString(1, currentUser); 
                int rowsAffected = pst.executeUpdate();
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Items added to your list");
                } else {
                    JOptionPane.showMessageDialog(null, "No items added to your list");
                } 
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
    }//GEN-LAST:event_spaghettiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recipe("currentUser").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutt;
    private javax.swing.JButton burger;
    private javax.swing.JButton cheeseballs;
    private javax.swing.JButton croissant;
    private javax.swing.JButton dumplings;
    private javax.swing.JButton friedrice;
    private javax.swing.JButton fries;
    private javax.swing.JButton garlic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kungpaosauce;
    private javax.swing.JButton pasta;
    private javax.swing.JButton pizza;
    private javax.swing.JButton sandwich;
    private javax.swing.JButton soup;
    private javax.swing.JButton spaghetti;
    private javax.swing.JButton sushi;
    // End of variables declaration//GEN-END:variables
}
